### ISSUE TITLE
Bug: Buttons not behaving as expected.

### ISSUE THREAD

**Issue by StrannikAD** [StardustCollective/molly_wallet#31]
There are a few buttons that don't work as expected.

- After creating a new wallet, on the Terms and Conditions screen. If you click `Close Application` (instead of agree), the application doesn't actually close. You just get kicked back to the main screen. I think the easiest solution is to change the wording to `Cancel` instead.

![image](https://user-images.githubusercontent.com/22587768/97558026-aa6d3180-1a2f-11eb-8129-1558104b59af.png)

**In Settings view:**

After clicking on `Wallet Information`, then `Browse`, and then **`Cancel`** - I get this screen:
![image](https://user-images.githubusercontent.com/22587768/97558250-f91acb80-1a2f-11eb-9180-7049524e3077.png)

**Expected Behaviour:** 
Cancel should just cancel with no error being thrown up. At the moment, it seems to be behaving as if you have hit apply.

**Comment by ffox77** [comment]
verified
