### ISSUE TITLE
Feature Request: Ability to Export JSON File from Wallet

### ISSUE THREAD

**Issue by StrannikAD** [StardustCollective/molly_wallet#49]
**Current Behaviour:**
Wallet does point to the location of the JSON file - but the user is unable to export the JSON file itself.

**Proposed New Behaviour:**
Have the ability to export the JSON file directly from the Molly Wallet - similar to Metamask. This could be located in the `Wallet Info `page

**Comment by ffox77** [comment]
The JSON file is already the exported version of the private key 🤷 
There is no need for additional action.
