### ISSUE TITLE
Unable to create wallet (save encrypted file on disk)

### ISSUE THREAD

**Issue by tonygustafsson** [StardustCollective/molly_wallet#54]
**Describe the bug**
When using the Linux build on Ubuntu I get the error "Unable to write encrypted keys to filesystem.". Doesn't matter if I'm running as a user or as sudo. I also tried storing it in other directories. The key alias cannot be reused though.

**To Reproduce**
1. Open app in Ubuntu
2. Click "Don't have a wallet yet? Create on here!"
3. Browse to the directory and name the file, add a unique key alias and keystore password. Name the wallet "Main".
4. Click "Create"

**Expected behavior**
I expected the key store to be saved on disk and that the wallet would open and give me the address and funds.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser Not relevant
 - Version 1.2.0

**Comment by ffox77** [comment]
Update to the latest version. v2.0 and greater do not use key alias.
