### ISSUE TITLE
Recent version of wallet does not support MacOS < 11.x

### ISSUE THREAD

**Issue by domol** [StardustCollective/molly_wallet#55]
**Describe the bug**
It is impossible to open wallet on Mac if its not BigSur. 

**Expected behavior**
Most recent version of the wallet is available for other OS in Mac.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Version 2.11

**Comment by ffox77** [comment]
Use the prior version. v2.1.0.
