### ISSUE TITLE
I see only a black window when I execute molly wallet

### ISSUE THREAD

**Issue by crocket** [StardustCollective/molly_wallet#56]
Operating System: Gentoo Linux
Window Manager: i3, sway

It used to work. After system upgrade, it shows only black screen.

I built wails with `go get -u github.com/wailsapp/wails/cmd/wails` and molly_wallet with `~/go/bin/wails build`.
The built binary shows a black window before and after system upgrade.

https://github.com/StardustCollective/molly_wallet/releases/download/v2.1.0-ubuntu/mollywallet-2.1.0-Ubuntu_18_04.gz shows a black window after system upgrade.

**Comment by ffox77** [comment]
The latest release now includes Linux build: https://github.com/StardustCollective/molly_wallet/releases/tag/v2.1.1

**Comment by crocket** [comment]
I tested the linux build for 2.1.1. The issue isn't fixed, yet. I'm using stargazer wallet for now.
stargazer wallet supports seed phrase and multiple addresses behind a seed phrase.
I wish molly wallet supported multiple addresses behind a seed phrase, too.
