### ISSUE TITLE
"wails build" fails with "stardust-collective/dag-wallet-sdk@0.1.3 is not in the npm registry"

### ISSUE THREAD

**Issue by tushartgupta** [StardustCollective/molly_wallet#58]
**Describe the bug**
"wails build" fails with "stardust-collective/dag-wallet-sdk@0.1.3 is not in the npm registry"

**To Reproduce**
1. git clone https://github.com/StardustCollective/molly_wallet.git
2. cd molly_wallet
3. wails build

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@stardust-collective/dag-wallet-sdk/-/dag-wallet-sdk-0.1.3.tgz
npm ERR! 404
npm ERR! 404  '@stardust-collective/dag-wallet-sdk@0.1.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'frontend'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs Monterey

**Comment by tushartgupta** [comment]
Hi @ffox77 If you can please help me with the above error.

**Comment by ffox77** [comment]
This package is no longer being maintained and there may be some challenges with getting it to build with outdated dependencies:

Something to try:

Edit the frontend/package.json and change the version on the dependency:

"@stardust-collective/dag-wallet-sdk": "0.1.6"
